# Raw experiment: Create raw forecast
loader:
    type: file
    # filenames: [ "data/air_temperature/5TB/2020030[1-4]T*Z.nc"]  # One file
    # filenames: [ "data/air_temperature/5TB/2020*1T*Z.nc"]    # 36 files
    # filenames: [ "data/air_temperature/5TB/202*01T*Z.nc"]    # 24 files
    filenames: [ "data/air_temperature/5TB/2020*T*Z.nc", "data/air_temperature/5TB/20210[12]*T*Z.nc"]
    omit_filenames: ["data/air_temperature/5TB/20210301T*Z.nc",
                "data/air_temperature/5TB/20210315T*Z.nc",
                "data/air_temperature/5TB/20210402T*Z.nc",
                "data/air_temperature/5TB/20210416T*Z.nc",
                "data/air_temperature/5TB/20210501T*Z.nc",
                "data/air_temperature/5TB/20210515T*Z.nc",
                "data/air_temperature/5TB/20210602T*Z.nc",
                "data/air_temperature/5TB/20210616T*Z.nc",
                "data/air_temperature/5TB/20210701T*Z.nc",
                "data/air_temperature/5TB/20210715T*Z.nc",
                "data/air_temperature/5TB/20210802T*Z.nc",
                "data/air_temperature/5TB/20210816T*Z.nc",
                "data/air_temperature/5TB/20210901T*Z.nc",
                "data/air_temperature/5TB/20210915T*Z.nc",
                "data/air_temperature/5TB/20211002T*Z.nc",
                "data/air_temperature/5TB/20211016T*Z.nc",
                "data/air_temperature/5TB/20211101T*Z.nc",
                "data/air_temperature/5TB/20211115T*Z.nc",
                "data/air_temperature/5TB/20211202T*Z.nc",
                "data/air_temperature/5TB/20211216T*Z.nc",
                "data/air_temperature/5TB/20220101T*Z.nc",
                "data/air_temperature/5TB/20220115T*Z.nc",
                "data/air_temperature/5TB/20220202T*Z.nc",
                "data/air_temperature/5TB/20220216T*Z.nc"
    ]
    predict_diff: False
    limit_predictors: ["air_temperature_0.1_2m", "air_temperature_2m", "air_temperature_0.9_2m", "altitude", "model_altitude"]
    patch_size: 512
    batch_size: 1
    with_leadtime: False
    num_parallel_calls: 12
    debug: False
loader_validation:
    type: file
    filenames: ["data/air_temperature/5TB/20210301T*Z.nc",
                "data/air_temperature/5TB/20210315T*Z.nc",
                "data/air_temperature/5TB/20210402T*Z.nc",
                "data/air_temperature/5TB/20210416T*Z.nc",
                "data/air_temperature/5TB/20210501T*Z.nc",
                "data/air_temperature/5TB/20210515T*Z.nc",
                "data/air_temperature/5TB/20210602T*Z.nc",
                "data/air_temperature/5TB/20210616T*Z.nc",
                "data/air_temperature/5TB/20210701T*Z.nc",
                "data/air_temperature/5TB/20210715T*Z.nc",
                "data/air_temperature/5TB/20210802T*Z.nc",
                "data/air_temperature/5TB/20210816T*Z.nc",
                "data/air_temperature/5TB/20210901T*Z.nc",
                "data/air_temperature/5TB/20210915T*Z.nc",
                "data/air_temperature/5TB/20211002T*Z.nc",
                "data/air_temperature/5TB/20211016T*Z.nc",
                "data/air_temperature/5TB/20211101T*Z.nc",
                "data/air_temperature/5TB/20211115T*Z.nc",
                "data/air_temperature/5TB/20211202T*Z.nc",
                "data/air_temperature/5TB/20211216T*Z.nc",
                "data/air_temperature/5TB/20220101T*Z.nc",
                "data/air_temperature/5TB/20220115T*Z.nc",
                "data/air_temperature/5TB/20220202T*Z.nc",
                "data/air_temperature/5TB/20220216T*Z.nc"
    ]
    limit_predictors: ["air_temperature_0.1_2m", "air_temperature_2m", "air_temperature_0.9_2m", "altitude", "model_altitude"]
    batch_size: 1
    predict_diff: False
    with_leadtime: False
    num_parallel_calls: 12
    debug: False
    x_range: [300,1068]
    y_range: [550,1062]
loader_test:
    type: file
    filenames: ["data/air_temperature/5TB/20210[3-9]*T*Z.nc",
                "data/air_temperature/5TB/20211*T*Z.nc",
                "data/air_temperature/5TB/2022*T*Z.nc"]
    limit_predictors: ["air_temperature_0.1_2m", "air_temperature_2m", "air_temperature_0.9_2m", "altitude", "model_altitude"]
    batch_size: 1
    predict_diff: False
    with_leadtime: False
    num_parallel_calls: 12
    debug: False
    x_range: [215, 1751]
    y_range: [50, 2098]
